@cross-borough @architecture @i18n @ai
Feature: Capsule LLM content + video pipeline boundary (CAP-ARCH-6)

  As a capsule-gradle producer
  I want the LLM-generated speaker notes to feed the single-language capsule video pipeline
  So that the CAP-ARCH content layer and the CAP-29 execution backend form one verifiable boundary

  Scenario: The composite content and videos task is registered with the capsule group
    Given a Capsule Arch Boundary Gradle project with a French source deck
    When I list the Gradle tasks in group capsule
    Then the capsule arch boundary task "generateCapsuleContentAndVideos" is listed in the output

  Scenario: The LLM content pipeline produces enriched speaker notes and a TTS script
    Given a Capsule Arch Boundary Gradle project with a French source deck
    And a mock Ollama LLM server proposing a valid content plan then enriched speaker notes
    When I run the capsule content generation task against the mock LLM
    Then the capsule arch boundary build succeeds
    And the capsule arch boundary build output logs "CAPSULE PIPELINE"
    And a speaker notes file "demo-speaker-notes.adoc" is generated by the capsule arch boundary build
    And a TTS script file "demo-script.txt" is generated by the capsule arch boundary build

  Scenario: The single-language video pipeline consumes the LLM-generated script and produces one WebM
    Given a Capsule Arch Boundary Gradle project with a French source deck and NoOp engines
    And a mock Ollama LLM server proposing a valid content plan then enriched speaker notes
    When I run the capsule content and videos task against the mock LLM
    Then the capsule arch boundary build succeeds
    And the capsule arch boundary build output logs "CAPSULE PIPELINE"
    And a TTS script file "demo_fr-script.txt" is generated by the capsule arch boundary build
    And a video file "demo_fr.webm" is generated by the capsule arch boundary video pipeline

  Scenario: The content and videos pipeline skips regeneration when the WebM already exists
    Given a Capsule Arch Boundary Gradle project with a French source deck and NoOp engines
    And a mock Ollama LLM server proposing a valid content plan then enriched speaker notes
    And an existing valid WebM artifact for language "fr"
    When I run the capsule content and videos task against the mock LLM
    Then the capsule arch boundary build succeeds
    And the build output reports the fr video is skipped as already rendered