package capsule

import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class AudioConversionUtilTest {

    @Test
    fun `wavToMp3 falls back to file copy when ffmpeg not available`(@TempDir tempDir: File) {
        val wavFile = tempDir.resolve("input.wav")
        wavFile.writeText("fake wav content")

        val mp3File = tempDir.resolve("output.mp3")

        AudioConversionUtil.wavToMp3(wavFile, mp3File, ffmpegPath = "/nonexistent/ffmpeg")

        assertTrue(mp3File.exists())
        assertEquals("fake wav content", mp3File.readText())
    }

    @Test
    fun `wavToMp3 falls back when ffmpeg returns non-zero exit code`(@TempDir tempDir: File) {
        val wavFile = tempDir.resolve("input.wav")
        wavFile.writeText("fake wav content")

        val mp3File = tempDir.resolve("output.mp3")

        // /bin/false always returns exit code 1 on Linux
        AudioConversionUtil.wavToMp3(wavFile, mp3File, ffmpegPath = "/bin/false")

        assertTrue(mp3File.exists())
        assertEquals("fake wav content", mp3File.readText())
    }

    @Test
    fun `wavToMp3 creates parent directories if needed`(@TempDir tempDir: File) {
        val wavFile = tempDir.resolve("input.wav")
        wavFile.writeText("fake wav content")

        val mp3File = tempDir.resolve("nested/deep/output.mp3")

        AudioConversionUtil.wavToMp3(wavFile, mp3File, ffmpegPath = "/nonexistent/ffmpeg")

        assertTrue(mp3File.exists())
        assertTrue(mp3File.parentFile.exists())
    }

    @Test
    @Tag("integration")
    fun `wavToMp3 converts wav to mp3 using ffmpeg`(@TempDir tempDir: File) {
        val wavFile = tempDir.resolve("input.wav")
        // Generate a real silent wav with ffmpeg for the test
        val genProc = ProcessBuilder(
            "ffmpeg", "-y", "-f", "lavfi", "-i", "anullsrc=r=44100:cl=mono",
            "-t", "0.1", "-acodec", "pcm_s16le", wavFile.absolutePath
        ).redirectErrorStream(true).start()
        genProc.waitFor()

        assertTrue(wavFile.exists(), "Test setup: wav file should be generated by ffmpeg")

        val mp3File = tempDir.resolve("output.mp3")

        AudioConversionUtil.wavToMp3(wavFile, mp3File)

        assertTrue(mp3File.exists())
        assertTrue(mp3File.length() > 0)
    }

    @Test
    @Tag("integration")
    fun `isAvailable returns true when ffmpeg in PATH`() {
        assertTrue(AudioConversionUtil.isAvailable())
    }

    @Test
    fun `isAvailable returns false when ffmpeg not found`() {
        assertFalse(AudioConversionUtil.isAvailable(ffmpegPath = "/nonexistent/ffmpeg"))
    }
}
